let activeBacktestId=null,activeBacktestIds=[];
async function B(p,o={}){let r=await fetch(p,{credentials:"same-origin",cache:"no-store",...o,headers:{"Content-Type":"application/json"}}),d=await r.json().catch(()=>({}));if(r.status===401){location.replace("/login");throw Error("authentication_required")}if(!r.ok)throw Error(d.error||"request_failed");return d}
function M(t,e=false){let n=document.querySelector("#backtest-status");if(n){n.textContent=t;n.style.color=e?"#d6a4a4":"var(--gold)"}}
function chart(points){let c=document.querySelector("#equity-chart");if(!c||!points?.length)return;c.width=Math.max(600,c.clientWidth)*devicePixelRatio;c.height=240*devicePixelRatio;let x=c.getContext("2d"),v=points.map(p=>+p.equity),mn=Math.min(...v),mx=Math.max(...v),pad=24*devicePixelRatio;x.clearRect(0,0,c.width,c.height);x.strokeStyle="#c7a86b";x.lineWidth=2*devicePixelRatio;x.beginPath();v.forEach((q,i)=>{let X=pad+i*(c.width-2*pad)/Math.max(1,v.length-1),Y=c.height-pad-(q-mn)*(c.height-2*pad)/Math.max(1,mx-mn);i?x.lineTo(X,Y):x.moveTo(X,Y)});x.stroke()}
function R(j){let r=j.result||{},m=r.metrics||{};document.querySelector("#backtest-job").textContent=`${j.status} · ${j.backtest_id||""} · version ${j.version_id||"—"}`;document.querySelector("#backtest-metrics").innerHTML=["trades","win_rate","net_r","net_profit","profit_factor","max_drawdown","expectancy_r","ending_balance"].map(k=>`<div class="stat"><small>${k.replaceAll("_"," ")}</small><strong>${m[k]??"—"}</strong></div>`).join("");chart(r.equity_curve);document.querySelector("#backtest-trades").innerHTML=(r.trades||[]).map(t=>`<tr><td>${t.side??""}</td><td>${t.entry_time??""}</td><td>${t.exit_time??""}</td><td>${t.outcome??""}</td><td>${t.r??""}</td><td>${t.pnl_money??""}</td><td>${t.cost_money??""}</td></tr>`).join("");document.querySelector("#backtest-result").textContent=JSON.stringify(r.diagnostics||{},null,2)}
const ASSETS={forex:["AUDCAD","AUDCHF","AUDJPY","AUDNZD","AUDUSD","CADCHF","CADJPY","CHFJPY","EURAUD","EURCAD","EURCHF","EURGBP","EURJPY","EURNZD","EURUSD","GBPAUD","GBPCAD","GBPCHF","GBPJPY","GBPNZD","GBPUSD","NZDCAD","NZDCHF","NZDJPY","NZDUSD","USDCAD","USDCHF","USDJPY"],indices:["US30","US100","US500","UK100","GER40","FRA40","EU50","JP225","AUS200","HK50"],metals:["XAUUSD","XAGUSD","XPTUSD","XPDUSD"]};
let assetGroup="forex";const selectedAssets=new Set(["EURUSD"]);const allAssets=()=>[...ASSETS.forex,...ASSETS.indices,...ASSETS.metals];
function visibleAssets(){let q=(document.querySelector("#asset-search")?.value||"").toUpperCase();return (assetGroup==="all"?allAssets():ASSETS[assetGroup]).filter(x=>!q||x.includes(q))}
function renderAssets(){let g=document.querySelector("#asset-grid");if(!g)return;g.innerHTML=visibleAssets().map(s=>`<label class="asset-chip ${selectedAssets.has(s)?"selected":""}"><input type="checkbox" value="${s}" ${selectedAssets.has(s)?"checked":""}><span>${s}</span></label>`).join("");g.querySelectorAll("input").forEach(i=>i.onchange=()=>{i.checked?selectedAssets.add(i.value):selectedAssets.delete(i.value);renderAssets()});document.querySelector("#asset-selected-count").textContent=`${selectedAssets.size} selected`}
document.querySelectorAll(".asset-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".asset-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");assetGroup=b.dataset.assetGroup;renderAssets()});document.querySelector("#asset-search")?.addEventListener("input",renderAssets);document.querySelector("#asset-select-visible")?.addEventListener("click",()=>{visibleAssets().forEach(x=>selectedAssets.add(x));renderAssets()});document.querySelector("#asset-clear")?.addEventListener("click",()=>{selectedAssets.clear();renderAssets()});renderAssets();
function bodyFor(f,symbol){return{strategy_id:(window.activeStrategyId||f.elements.strategy_id.value).trim(),symbol,timeframe:f.elements.timeframe.value,date_from:f.elements.date_from.value,date_to:f.elements.date_to.value,starting_balance:+f.elements.starting_balance.value,spread_pips:+f.elements.spread_pips.value,commission_per_lot:+f.elements.commission_per_lot.value,slippage_pips:+f.elements.slippage_pips.value}}
function rows(symbols){let b=document.querySelector("#portfolio-backtest-summary"),r=document.querySelector("#portfolio-backtest-rows");b.hidden=false;r.innerHTML=symbols.map(s=>`<div class="portfolio-asset-row" data-symbol="${s}"><strong>${s}</strong><span class="state">WAITING</span><span class="detail"></span><span class="id"></span></div>`).join("")}
function upd(s,state,detail="",id=""){let r=document.querySelector(`.portfolio-asset-row[data-symbol="${s}"]`);if(r){r.querySelector(".state").textContent=state;r.querySelector(".detail").textContent=detail;r.querySelector(".id").textContent=id}}
document.querySelector("#backtest-form")?.addEventListener("submit",async e=>{e.preventDefault();let f=e.currentTarget,s=(window.activeStrategyId||f.elements.strategy_id.value).trim(),symbols=[...selectedAssets];if(!s)return M("Create/approve a strategy first.",true);if(!symbols.length)return M("Select at least one asset.",true);activeBacktestIds=[];rows(symbols);for(let symbol of symbols){try{M(`Creating ${symbol}...`);let j=await B("/api/backtests",{method:"POST",body:JSON.stringify(bodyFor(f,symbol))});activeBacktestIds.push({symbol,backtest_id:j.backtest_id});activeBacktestId=j.backtest_id;upd(symbol,j.status||"QUEUED","Ready",j.backtest_id)}catch(x){upd(symbol,"FAILED",x.message)}}M(`Created ${activeBacktestIds.length}/${symbols.length}. Press Run selected assets.`)});
document.querySelector("#run-backtest")?.addEventListener("click",async()=>{if(!activeBacktestIds.length)return M("Create selected backtests first.",true);let ok=0,fail=0,last=null;for(let i=0;i<activeBacktestIds.length;i++){let a=activeBacktestIds[i];try{M(`Running ${i+1}/${activeBacktestIds.length}: ${a.symbol}`);upd(a.symbol,"RUNNING","Historical test in progress",a.backtest_id);let j=await B(`/api/backtests/${a.backtest_id}/run`,{method:"POST",body:"{}"});last=j;let m=j.result?.metrics||{};upd(a.symbol,j.status||"COMPLETED",`Trades ${m.trades??"—"} · WR ${m.win_rate??"—"} · Net R ${m.net_r??"—"} · PF ${m.profit_factor??"—"}`,a.backtest_id);ok++}catch(x){fail++;upd(a.symbol,"FAILED",x.message,a.backtest_id)}}if(last)R(last);M(`Finished: ${ok} completed, ${fail} failed.`)});
const q=new URLSearchParams(location.search).get("strategy_id");if(q){let i=document.querySelector('#backtest-form [name="strategy_id"]');if(i)i.value=q}
