const DASH_LANG_STORAGE = "velmontaire_language";

const DASH_TRANSLATIONS = {
  ru: {
    "Workspace":"Рабочее пространство",
    "Statistics":"Статистика",
    "Account snapshot":"Снимок счёта",
    "Dashboard overview":"Обзор статистики",
    "The compact performance view from the homepage — now connected to the real workspace data.":"Тот самый компактный блок статистики с главной — теперь подключён к реальным данным рабочего пространства.",
    "PAPER / LIVE":"PAPER / LIVE",
    "ALL SYSTEMS OK":"ВСЕ СИСТЕМЫ В НОРМЕ",
    "Equity":"Средства",
    "Account data":"Данные счёта",
    "Equity Curve":"Кривая капитала",
    "Recent Activity":"Последние события",
    "Workspace events":"События рабочего пространства",
    "No recent execution activity yet.":"Событий исполнения пока нет.",
    "Waiting for closed-trade data":"Ожидаем данные закрытых сделок",
    "No runtime risk snapshot yet":"Нет последнего снимка риска runtime",
    "Performance":"Результаты",
    "Daily performance, trading quality and account health.":"Ежедневные результаты, качество торговли и состояние счёта.",
    "DAILY PERFORMANCE / ACCOUNT ANALYTICS":"ЕЖЕДНЕВНЫЕ РЕЗУЛЬТАТЫ / АНАЛИТИКА СЧЁТА",
    "Know exactly how every trading day performed.":"Смотри результат каждого торгового дня отдельно.",
    "See daily P/L, win rate, profit factor, drawdown and trade count from the execution data generated by your own workspace.":"Смотри P/L за день, win rate, profit factor, просадку и количество сделок по реальным данным исполнения.",
    "Daily history":"История по дням",
    "No fake data":"Без выдуманных данных",
    "Execution-log source":"Источник: execution logs",
    "Daily trading statistics":"Ежедневная статистика торговли",
    "Every trading day in one place. Values are built from your execution logs — no demo performance is inserted.":"Каждый торговый день в одном месте. Данные строятся из execution logs — демонстрационная прибыль не подставляется.",
    "Refresh":"Обновить",
    "Current Equity":"Текущие средства",
    "Waiting for account data":"Ожидаем данные счёта",
    "Today's P/L":"P/L сегодня",
    "0 trades today":"0 сделок сегодня",
    "Win Rate":"Win Rate",
    "Selected period":"Выбранный период",
    "Profit Factor":"Profit Factor",
    "Open Risk":"Открытый риск",
    "Latest runtime snapshot":"Последний снимок runtime",
    "Performance curve":"График результатов",
    "Daily P/L":"P/L по дням",
    "Period summary":"Итоги периода",
    "Trading quality":"Качество торговли",
    "Trades":"Сделки",
    "Wins":"Победы",
    "Losses":"Убытки",
    "Net P/L":"Чистый P/L",
    "Net R":"Итог R",
    "Max DD":"Макс. просадка",
    "Source":"Источник",
    "Execution logs":"Execution logs",
    "Day by day":"По дням",
    "Daily history":"История по дням",
    "Click a day to see its result without searching through raw runtime logs.":"Результат каждого дня виден без поиска по сырым runtime-логам.",
    "Date":"Дата",
    "W / L":"П / У",
    "Win rate":"Win rate",
    "No trading statistics yet":"Торговой статистики пока нет",
    "Once PAPER/LIVE execution logs contain closed-trade P/L, daily results will appear here automatically.":"Как только в PAPER/LIVE execution logs появятся закрытые сделки с P/L, ежедневные результаты отобразятся автоматически.",
    "Overview":"Обзор",
    "Strategy":"Стратегия",
    "Backtest":"Бэктест",
    "Compare":"Сравнение",
    "Prop Rules":"Правила Prop",
    "MT5":"MT5",
    "PAPER":"PAPER",
    "LIVE":"LIVE",
    "Safety":"Безопасность",
    "Billing":"Тарифы",
    "Telemetry":"Мониторинг",
    "Sign out":"Выйти",
    "Operator":"Пользователь",
    "Notifications":"Уведомления",

    "Control center":"Центр управления",
    "Your trading system, runtime and account health in one place.":"Стратегии, исполнение и состояние счёта — в одном месте.",
    "VELMONTAIRE / OVERVIEW":"VELMONTAIRE / ОБЗОР",
    "One workspace. Every execution boundary visible.":"Одно пространство. Полный контроль исполнения.",
    "Move from strategy design to backtest, broker connection and controlled runtime without losing sight of safety.":"От создания стратегии до бэктеста, подключения брокера и контролируемого запуска — без потери контроля над безопасностью.",
    "FAIL-CLOSED CORE":"FAIL-CLOSED ЯДРО",
    "IMMUTABLE VERSIONS":"НЕИЗМЕНЯЕМЫЕ ВЕРСИИ",
    "PAPER → LIVE":"PAPER → LIVE",
    "Balance":"Баланс",
    "Equity":"Средства",
    "Daily P/L":"P/L за день",
    "Drawdown":"Просадка",
    "System readiness":"Готовность системы",
    "Execution stack":"Контур исполнения",
    "Strategy parsing, backtest, broker and runtime safety are visible at a glance.":"Парсер стратегии, бэктест, брокер и безопасность runtime видны сразу.",
    "Core online":"Ядро работает",
    "Fail-closed":"Fail-closed",
    "Quick action":"Быстрое действие",
    "Build a strategy":"Создать стратегию",
    "Describe the logic naturally, review structured rules, then compile a version.":"Опиши логику обычным языком, проверь структурированные правила и создай версию.",
    "Open Strategy Builder":"Открыть конструктор",
    "Runtime guard":"Защита runtime",
    "Safety first":"Безопасность прежде всего",
    "Recovery, reconciliation and duplicate protection stay in front of execution.":"Восстановление, сверка состояния и защита от дублей работают до исполнения.",
    "Open Safety Center":"Открыть Safety Center",
    "Start here":"Начни здесь",
    "Set up VELMONTAIRE in 5 steps":"Настрой VELMONTAIRE за 5 шагов",
    "You should never have to hunt through the workspace. Follow this path once, then operate from the pages you need.":"Ничего искать не нужно. Пройди этот путь один раз, затем используй нужные разделы.",
    "GUIDED SETUP":"ПОШАГОВАЯ НАСТРОЙКА",
    "Choose a plan":"Выбери тариф",
    "See limits, LIVE access and prop support.":"Сразу увидишь лимиты, LIVE и поддержку prop.",
    "Choose account rules":"Выбери тип счёта",
    "Personal, CFD prop or futures prop.":"Личный, CFD prop или futures prop.",
    "Connect MT5":"Подключи MT5",
    "Add login, server and password, then verify.":"Введи логин, сервер и пароль, затем проверь соединение.",
    "Create strategy":"Создай стратегию",
    "Describe, clarify, review and approve.":"Опиши, уточни, проверь и подтверди.",
    "PAPER → LIVE":"PAPER → LIVE",
    "Dry-run first, authorize LIVE only when ready.":"Сначала PAPER, затем LIVE только после готовности.",
    "Customer journey":"Путь пользователя",
    "Production path":"Путь к запуску",

    "AI strategy builder":"AI-конструктор стратегии",
    "Strategy":"Стратегия",
    "Describe the system naturally, then control every resolved rule.":"Опиши систему обычным языком и контролируй каждое правило.",
    "BUILD / STRUCTURE / COMPILE":"СОЗДАНИЕ / СТРУКТУРА / КОМПИЛЯЦИЯ",
    "Turn trading language into an executable strategy.":"Преврати торговую идею в исполняемую стратегию.",
    "VELMONTAIRE parses the idea, surfaces ambiguity and keeps every important rule reviewable before compilation.":"VELMONTAIRE разбирает идею, показывает неоднозначности и позволяет проверить каждое важное правило до компиляции.",
    "Multilingual parser":"Мультиязычный парсер",
    "Structured controls":"Структурированные настройки",
    "Custom capabilities":"Пользовательские правила",
    "AI Strategy Builder":"AI-конструктор стратегии",
    "Describe once. Control every rule.":"Опиши один раз. Контролируй каждое правило.",
    "AI parses natural language, fills structured settings and surfaces unresolved rules instead of guessing.":"AI разбирает обычный язык, заполняет структурированные настройки и показывает неуточнённые правила вместо догадок.",
    "AI → STRUCTURED":"AI → СТРУКТУРА",
    "Strategy name":"Название стратегии",
    "Strategy library":"Библиотека стратегий",
    "My strategies":"Мои стратегии",
    "Every strategy you create is kept here so you can reopen it without searching for IDs.":"Все созданные стратегии сохраняются здесь — их можно открыть без поиска ID.",
    "No strategies yet. Create your first strategy above.":"Стратегий пока нет. Создай первую стратегию выше.",
    "Open":"Открыть",
    "No active version":"Нет активной версии",
    "Trading rules":"Торговые правила",
    "Parse & create strategy":"Разобрать и создать стратегию",
    "Structured controls preview":"Предпросмотр настроек",
    "Market":"Рынок",
    "Direction":"Направление",
    "Entry timeframe":"Таймфрейм входа",
    "Entry model":"Модель входа",
    "Risk / trade":"Риск на сделку",
    "Take profit":"Тейк-профит",
    "Management":"Управление",
    "Unresolved":"Не уточнено",
    "These controls are the target UX layer: AI-filled, human-reviewable and editable before compilation.":"AI заполняет эти настройки, пользователь проверяет и редактирует их до компиляции.",
    "Capability Lab":"Лаборатория возможностей",
    "Can't find a rule?":"Не хватает правила?",
    "Describe the missing condition. Existing modules are reused first; genuinely new capabilities enter a controlled future-release queue.":"Опиши недостающее условие. Сначала система попробует собрать его из существующих модулей; действительно новая возможность попадёт в контролируемую очередь разработки.",
    "SAFE EXTENSION":"БЕЗОПАСНОЕ РАСШИРЕНИЕ",
    "What do you need?":"Что тебе нужно?",
    "Analyze capability":"Проанализировать возможность",
    "No requests yet.":"Запросов пока нет.",

    "Validation":"Проверка",
    "Backtest":"Бэктест",
    "Test an exact immutable strategy version against historical data.":"Проверь точную неизменяемую версию стратегии на исторических данных.",
    "EVIDENCE BEFORE EXECUTION":"ПРОВЕРКА ДО ИСПОЛНЕНИЯ",
    "See how the strategy behaves before it touches runtime.":"Посмотри, как стратегия ведёт себя до запуска runtime.",
    "Run controlled historical validation, inspect risk-adjusted metrics and audit every trade.":"Проведи историческую проверку, изучи метрики и каждую сделку.",
    "Exact version":"Точная версия",
    "Equity curve":"Кривая капитала",
    "Trade audit":"Аудит сделок",
    "Validation & performance":"Проверка и результаты",
    "Strategy ID":"ID стратегии",
    "Symbol":"Инструмент",
    "Timeframe":"Таймфрейм",
    "Date from":"Дата от",
    "Date to":"Дата до",
    "Starting balance":"Начальный баланс",
    "Spread (pips)":"Спред (пипсы)",
    "Commission / lot":"Комиссия / лот",
    "Slippage (pips)":"Проскальзывание (пипсы)",
    "Create backtest":"Создать бэктест",
    "Run":"Запустить",
    "Side":"Сторона",
    "Entry time":"Время входа",
    "Exit time":"Время выхода",
    "Outcome":"Результат",
    "Costs":"Издержки",

    "Version analysis":"Анализ версий",
    "Compare":"Сравнение",
    "Compare candidate strategy versions under the same conditions.":"Сравни версии стратегии в одинаковых условиях.",
    "VERSION INTELLIGENCE":"АНАЛИЗ ВЕРСИЙ",
    "Know exactly what changed — and whether it improved.":"Точно знай, что изменилось и стало ли лучше.",
    "Compare performance deltas and schema changes without mixing incompatible test conditions.":"Сравни изменения метрик и схемы без смешивания разных условий теста.",
    "Same conditions":"Одинаковые условия",
    "Metric delta":"Изменение метрик",
    "Schema diff":"Изменения схемы",
    "Version comparison":"Сравнение версий",
    "Compare immutable versions":"Сравнить неизменяемые версии",
    "Previous backtest ID":"ID прошлого бэктеста",
    "Candidate backtest ID":"ID нового бэктеста",
    "Compare versions":"Сравнить версии",
    "Metric":"Метрика",
    "Previous":"Предыдущая",
    "Candidate":"Кандидат",
    "Delta":"Изменение",
    "Schema changes":"Изменения схемы",

    "Account environment":"Среда счёта",
    "Prop Rules":"Правила Prop",
    "Configure verified account constraints and pre-trade compliance.":"Настрой проверенные ограничения счёта и предторговые проверки.",
    "POLICY / RISK / COMPLIANCE":"ПРАВИЛА / РИСК / COMPLIANCE",
    "Trade inside the account rules — not around them.":"Торгуй внутри правил аккаунта, а не в обход них.",
    "Keep prop policy server-owned while exposing the limits and checks the operator actually needs.":"Правила prop хранятся на сервере, а пользователь видит нужные ограничения и проверки.",
    "CFD props":"CFD prop",
    "Futures props":"Futures prop",
    "News + risk checks":"Новости + риск",
    "Personal account or Prop Firm?":"Личный счёт или Prop Firm?",
    "Select the environment once. VELMONTAIRE applies the correct account constraints before execution.":"Выбери тип счёта один раз. VELMONTAIRE применит нужные ограничения до исполнения.",
    "STEP 2 / ACCOUNT RULES":"ШАГ 2 / ПРАВИЛА СЧЁТА",
    "Personal account":"Личный счёт",
    "No prop-specific limits. You still use strategy and runtime risk controls.":"Без prop-ограничений. Риск-контроль стратегии и runtime остаётся активным.",
    "Prop Firm account":"Prop-счёт",
    "Select firm, program, phase and account size. Then connect that prop MT5 account.":"Выбери фирму, программу, фазу и размер счёта, затем подключи именно этот MT5.",
    "MT5 comes next →":"Далее MT5 →",
    "Account type":"Тип счёта",
    "Personal / No Prop Rules":"Личный / без Prop-правил",
    "Prop Firm":"Prop Firm",
    "Firm":"Фирма",
    "Program":"Программа",
    "Stage / Phase":"Этап / фаза",
    "Account Size":"Размер счёта",
    "Apply Prop Rules":"Применить Prop-правила",
    "Not configured":"Не настроено",
    "After rules are selected":"После выбора правил",
    "Connect the exact MT5 account these rules belong to.":"Подключи именно тот MT5-счёт, к которому относятся эти правила.",
    "For a prop account, use the login/server/password provided by the prop firm for that challenge or funded account.":"Для prop-счёта используй логин, сервер и пароль, которые фирма выдала для этого challenge или funded account.",
    "Continue to MT5 →":"Перейти к MT5 →",
    "News compliance":"Проверка новостей",
    "Pre-trade news check":"Проверка новостей перед сделкой",
    "Action":"Действие",
    "UTC timestamp":"Время UTC",
    "Normalized events JSON":"События JSON",
    "Check News Compliance":"Проверить новости",
    "Prop risk compliance":"Prop риск-контроль",
    "Account safety check":"Проверка безопасности счёта",
    "Requested risk amount":"Запрошенный риск",
    "Weekend context":"Выходные",
    "Account snapshot JSON":"Состояние счёта JSON",
    "Check Prop Risk":"Проверить риск",

    "Broker boundary":"Контур брокера",
    "MT5":"MT5",
    "Manage the verified MetaTrader connection used by PAPER and LIVE.":"Управляй проверенным подключением MetaTrader для PAPER и LIVE.",
    "BROKER CONNECTIVITY":"ПОДКЛЮЧЕНИЕ БРОКЕРА",
    "A controlled bridge between VELMONTAIRE and MT5.":"Контролируемый мост между VELMONTAIRE и MT5.",
    "Credentials remain behind the secure boundary and execution modes depend on verified connectivity.":"Данные подключения остаются в защищённом контуре, а запуск зависит от подтверждённого соединения.",
    "Secure credentials":"Защищённые данные",
    "Connection test":"Проверка соединения",
    "Runtime boundary":"Контур runtime",
    "Broker connection":"Подключение брокера",
    "Connect your MT5 account":"Подключи свой MT5-счёт",
    "Works for a personal MT5 account and for a prop-firm MT5 account. VELMONTAIRE needs the credentials issued for that exact trading account.":"Подходит и для личного MT5, и для prop MT5. Нужны данные именно того торгового счёта, который будет использоваться.",
    "STEP 3 / VERIFIED CONNECTION":"ШАГ 3 / ПРОВЕРЕННОЕ ПОДКЛЮЧЕНИЕ",
    "Use the MT5 login/server/password from your broker.":"Используй логин, сервер и пароль MT5 от брокера.",
    "Prop account":"Prop-счёт",
    "First select the prop rules, then use the prop firm's MT5 credentials here.":"Сначала выбери prop-правила, затем введи здесь MT5-данные от prop-фирмы.",
    "Configure Prop Rules →":"Настроить Prop Rules →",
    "MT5 login":"Логин MT5",
    "The numeric account login from MT5 / broker / prop dashboard.":"Числовой логин счёта из MT5, брокера или prop-кабинета.",
    "MT5 server":"Сервер MT5",
    "Must match the server name exactly as shown in MT5.":"Название сервера должно полностью совпадать с MT5.",
    "MT5 password":"Пароль MT5",
    "Use the trading password for this account. It is cleared from the form after save.":"Используй торговый пароль этого счёта. После сохранения поле очищается.",
    "1. Save connection":"1. Сохранить подключение",
    "2. Test connection":"2. Проверить подключение",
    "Connection status":"Статус подключения",
    "Not configured yet.":"Пока не настроено.",
    "No verified MT5 connection.":"Нет проверенного MT5-подключения.",
    "What happens next?":"Что дальше?",
    "Save credentials":"Сохрани данные",
    "Creates the broker connection record.":"Создаёт запись подключения брокера.",
    "Verify connection":"Проверь соединение",
    "VELMONTAIRE checks that the account can be reached.":"VELMONTAIRE проверяет доступность счёта.",
    "Create / approve strategy":"Создай / подтверди стратегию",
    "The runtime needs an approved immutable strategy version.":"Runtime нужна подтверждённая неизменяемая версия стратегии.",
    "Start PAPER":"Запусти PAPER",
    "Run the production path without LIVE authority.":"Проверь production-путь без LIVE-доступа.",
    "Authorize LIVE":"Разреши LIVE",
    "Only after all safety prerequisites are satisfied.":"Только после выполнения всех требований безопасности.",
    "Continue to PAPER →":"Перейти к PAPER →",

    "Dry-run execution":"Тестовое исполнение",
    "Run the approved strategy through the production runtime without LIVE authority.":"Запусти подтверждённую стратегию через production runtime без LIVE-доступа.",
    "PRODUCTION LOGIC / ZERO LIVE AUTHORITY":"PRODUCTION ЛОГИКА / БЕЗ LIVE-ДОСТУПА",
    "Test the runtime, not only the strategy.":"Проверь runtime, а не только стратегию.",
    "Use the same guarded execution path while removing live-market authority from the equation.":"Используй тот же защищённый путь исполнения, но без доступа к реальному рынку.",
    "Approved version":"Подтверждённая версия",
    "Runtime state":"Состояние runtime",
    "No live authority":"Без LIVE-доступа",
    "PAPER runtime":"PAPER runtime",
    "Controlled dry-run":"Контролируемый тестовый запуск",
    "No LIVE authority":"Без LIVE-доступа",
    "Bot ID":"ID бота",
    "Approved strategy version":"Подтверждённая версия стратегии",
    "Start PAPER":"Запустить PAPER",
    "PAPER stopped.":"PAPER остановлен.",

    "Live execution":"LIVE-исполнение",
    "Explicit authorization and controlled execution for the live account.":"Явное разрешение и контролируемое исполнение на реальном счёте.",
    "PROTECTED EXECUTION":"ЗАЩИЩЁННОЕ ИСПОЛНЕНИЕ",
    "LIVE starts only when every prerequisite is proven.":"LIVE запускается только после подтверждения всех условий.",
    "Connection, strategy version, operator confirmation and runtime safety must align before execution is allowed.":"Подключение, версия стратегии, подтверждение пользователя и безопасность runtime должны быть готовы до запуска.",
    "Explicit confirmation":"Явное подтверждение",
    "Pause / Stop":"Пауза / Стоп",
    "Revocable authority":"Отзыв разрешения",
    "LIVE runtime":"LIVE runtime",
    "Explicit authorization":"Явное разрешение",
    "Protected":"Защищено",
    "Strategy version ID":"ID версии стратегии",
    "Verified MT5 connection ID":"ID проверенного MT5",
    "Confirmation phrase":"Фраза подтверждения",
    "Confirm LIVE":"Подтвердить LIVE",
    "Start LIVE":"Запустить LIVE",
    "Pause":"Пауза",
    "Stop":"Стоп",
    "Refresh":"Обновить",
    "Revoke LIVE":"Отозвать LIVE",
    "LIVE not authorized.":"LIVE не разрешён.",

    "Production safety":"Production-безопасность",
    "Safety":"Безопасность",
    "Inspect failure state, recovery and reconciliation before new entries.":"Проверяй состояние ошибок, восстановление и сверку до новых входов.",
    "FAIL-CLOSED CONTROL":"FAIL-CLOSED КОНТРОЛЬ",
    "Uncertain state means no new trade.":"Неопределённое состояние — никаких новых сделок.",
    "Disconnects, restart ambiguity and recovery failures stay visible and block unsafe continuation.":"Отключения, неопределённость после перезапуска и ошибки восстановления блокируют небезопасное продолжение.",
    "Crash recovery":"Восстановление после сбоя",
    "Reconciliation":"Сверка состояния",
    "Entry blocking":"Блокировка входов",
    "Failure & recovery":"Ошибки и восстановление",
    "RUNTIME STATUS UNKNOWN":"СТАТУС RUNTIME НЕИЗВЕСТЕН",
    "Disconnects and uncertain restart state block new entries until reconciliation succeeds.":"Отключения и неопределённое состояние после рестарта блокируют новые входы до успешной сверки.",
    "Connection status":"Статус соединения",
    "Disconnect event":"Событие отключения",
    "Reconnect recovery":"Восстановление соединения",
    "Restart recovery":"Восстановление после рестарта",
    "Refresh safety state":"Обновить состояние",

    "Plan management":"Управление тарифом",
    "Billing":"Тарифы",
    "Subscription, usage and product entitlements in one surface.":"Подписка, использование и доступные функции — на одной странице.",
    "PLAN / ACCESS / USAGE":"ТАРИФ / ДОСТУП / ИСПОЛЬЗОВАНИЕ",
    "Know exactly what the workspace can use.":"Сразу видно, что доступно в твоём тарифе.",
    "Review subscription state, current usage and the capabilities unlocked by each plan.":"Проверь подписку, текущее использование и функции каждого тарифа.",
    "Entitlements":"Возможности",
    "Usage":"Использование",
    "Sandbox checkout":"Тестовая оплата",
    "Plan & billing":"Тариф и подписка",
    "Choose the plan that matches how you trade":"Выбери тариф под свой способ торговли",
    "Prices, limits and important features are visible here immediately. No hidden comparison page.":"Цены, лимиты и ключевые функции видны сразу — ничего искать не нужно.",
    "Refresh account":"Обновить аккаунт",
    "Current subscription":"Текущая подписка",
    "Loading…":"Загрузка…",
    "Checking your account.":"Проверяем аккаунт.",
    "Monthly pricing shown · annual equivalent is also displayed":"Показана месячная цена · рядом указан эквивалент при оплате за год",
    "Build and validate strategies.":"Создание и проверка стратегий.",
    "START":"СТАРТ",
    "Build and validate strategies.":"Создавай и проверяй стратегии.",
    "Build and validate strategies.":"Создавай и проверяй стратегии.",
    "For serious personal + prop trading.":"Для серьёзной личной и prop-торговли.",
    "POPULAR":"ПОПУЛЯРНЫЙ",
    "Higher limits for multi-account operation.":"Повышенные лимиты для нескольких аккаунтов.",
    "SCALE":"МАСШТАБ",
    "MOST USEFUL":"ОПТИМАЛЬНЫЙ",
    "Choose CORE":"Выбрать CORE",
    "Choose PRO":"Выбрать PRO",
    "Choose ELITE":"Выбрать ELITE",
    "At a glance":"Коротко",
    "What changes between plans?":"Чем отличаются тарифы?",
    "Feature":"Функция",
    "AI Strategy Builder":"AI-конструктор стратегии",
    "PAPER trading":"PAPER-торговля",
    "Prop-firm rules":"Правила Prop Firm",
    "LIVE execution":"LIVE-исполнение",
    "Advanced analytics":"Расширенная аналитика",
    "Priority support":"Приоритетная поддержка",
    "Checkout currently uses Paddle Sandbox in the development environment.":"В среде разработки checkout работает через Paddle Sandbox.",

    "Observability":"Мониторинг",
    "Telemetry":"Мониторинг",
    "Monitor runtime health and operator-visible production state.":"Следи за состоянием runtime и production-системы.",
    "HEALTH / EVENTS / READINESS":"СОСТОЯНИЕ / СОБЫТИЯ / ГОТОВНОСТЬ",
    "See the system state before it becomes a problem.":"Увидь проблему до того, как она повлияет на исполнение.",
    "Operational health, recovery readiness and execution safety converge into one monitoring surface.":"Состояние системы, готовность восстановления и безопасность исполнения собраны в одном месте.",
    "Runtime health":"Состояние runtime",
    "Recovery stack":"Восстановление",
    "Operator feed":"Лента событий",
    "Monitoring":"Мониторинг",
    "Operational health, latency and fail-closed signals converge here.":"Здесь собраны состояние системы, задержки и fail-closed сигналы.",
    "API":"API",
    "ONLINE":"РАБОТАЕТ",
    "Authenticated application surface":"Авторизованный API платформы",
    "Runtime":"Runtime",
    "GUARDED":"ЗАЩИЩЁН",
    "Transaction + idempotency boundary":"Транзакции + защита от дублей",
    "Recovery":"Восстановление",
    "READY":"ГОТОВО",
    "Checkpoint + journal reconciliation":"Checkpoint + journal + сверка",
    "Execution":"Исполнение",
    "SETUP":"НАСТРОЙКА",
    "Starts only after explicit authorization":"Запускается только после явного разрешения",
    "Recent system activity":"Последние события",
    "Workspace initialized":"Рабочее пространство запущено",
    "Session and entitlement checks are active.":"Проверки сессии и доступа активны.",
    "Fail-closed runtime enabled":"Fail-closed runtime включён",
    "Unsafe state transitions remain blocked.":"Небезопасные переходы состояния заблокированы.",
    "Recovery stack available":"Система восстановления готова",
    "Checkpoint, journal and replay components are installed.":"Checkpoint, журнал и replay доступны.",
    "NOW":"СЕЙЧАС"
  },

  uk: {}
};

// Ukrainian is intentionally derived from Russian only where an explicit Ukrainian
// translation is provided below. Anything missing stays in English rather than
// being silently mistranslated.
Object.assign(DASH_TRANSLATIONS.uk, {
  "Workspace":"Робочий простір","Statistics":"Статистика",
  "Account snapshot":"Знімок рахунку","Dashboard overview":"Огляд статистики",
  "The compact performance view from the homepage — now connected to the real workspace data.":"Той самий компактний блок статистики з головної — тепер підключений до реальних даних робочого простору.",
  "ALL SYSTEMS OK":"УСІ СИСТЕМИ В НОРМІ","Equity Curve":"Крива капіталу","Recent Activity":"Останні події",
  "Workspace events":"Події робочого простору","No recent execution activity yet.":"Подій виконання поки немає.","Performance":"Результати",
  "Daily performance, trading quality and account health.":"Щоденні результати, якість торгівлі та стан рахунку.",
  "Know exactly how every trading day performed.":"Переглядай результат кожного торгового дня окремо.",
  "Daily trading statistics":"Щоденна статистика торгівлі","Refresh":"Оновити",
  "Current Equity":"Поточні кошти","Today's P/L":"P/L сьогодні","Win Rate":"Win Rate","Profit Factor":"Profit Factor",
  "Open Risk":"Відкритий ризик","Performance curve":"Графік результатів","Daily P/L":"P/L за днями",
  "Period summary":"Підсумок періоду","Trading quality":"Якість торгівлі","Trades":"Угоди","Wins":"Перемоги",
  "Losses":"Збитки","Net P/L":"Чистий P/L","Net R":"Підсумок R","Max DD":"Макс. просадка",
  "Day by day":"За днями","Daily history":"Історія за днями","Date":"Дата","W / L":"П / З","Win rate":"Win rate","Overview":"Огляд","Strategy":"Стратегія","Backtest":"Бектест",
  "Compare":"Порівняння","Prop Rules":"Правила Prop","Safety":"Безпека","Billing":"Тарифи",
  "Telemetry":"Моніторинг","Sign out":"Вийти","Operator":"Користувач","Notifications":"Сповіщення",
  "Control center":"Центр керування",
  "Your trading system, runtime and account health in one place.":"Стратегії, виконання та стан рахунку — в одному місці.",
  "VELMONTAIRE / OVERVIEW":"VELMONTAIRE / ОГЛЯД",
  "One workspace. Every execution boundary visible.":"Один простір. Повний контроль виконання.",
  "Move from strategy design to backtest, broker connection and controlled runtime without losing sight of safety.":"Від створення стратегії до бектесту, підключення брокера та контрольованого запуску — без втрати контролю над безпекою.",
  "Balance":"Баланс","Equity":"Кошти","Daily P/L":"P/L за день","Drawdown":"Просадка",
  "System readiness":"Готовність системи","Execution stack":"Контур виконання","Core online":"Ядро працює",
  "Quick action":"Швидка дія","Build a strategy":"Створити стратегію","Open Strategy Builder":"Відкрити конструктор",
  "Runtime guard":"Захист runtime","Safety first":"Безпека передусім","Open Safety Center":"Відкрити Safety Center",
  "Start here":"Почни тут","Set up VELMONTAIRE in 5 steps":"Налаштуй VELMONTAIRE за 5 кроків",
  "You should never have to hunt through the workspace. Follow this path once, then operate from the pages you need.":"Нічого шукати не потрібно. Пройди цей шлях один раз, а далі користуйся потрібними розділами.",
  "GUIDED SETUP":"ПОКРОКОВЕ НАЛАШТУВАННЯ","Choose a plan":"Обери тариф","Choose account rules":"Обери тип рахунку",
  "Connect MT5":"Підключи MT5","Create strategy":"Створи стратегію","Dry-run first, authorize LIVE only when ready.":"Спочатку PAPER, потім LIVE лише після готовності.",
  "Customer journey":"Шлях користувача","Production path":"Шлях до запуску",

  "AI strategy builder":"AI-конструктор стратегії","Describe the system naturally, then control every resolved rule.":"Опиши систему звичайною мовою та контролюй кожне правило.",
  "Turn trading language into an executable strategy.":"Перетвори торгову ідею на виконувану стратегію.",
  "Multilingual parser":"Багатомовний парсер","Structured controls":"Структуровані налаштування","Custom capabilities":"Користувацькі правила",
  "Describe once. Control every rule.":"Опиши один раз. Контролюй кожне правило.",
  "Strategy name":"Назва стратегії","Strategy library":"Бібліотека стратегій","My strategies":"Мої стратегії","Every strategy you create is kept here so you can reopen it without searching for IDs.":"Усі створені стратегії зберігаються тут — їх можна відкрити без пошуку ID.","No strategies yet. Create your first strategy above.":"Стратегій поки немає. Створи першу стратегію вище.","Open":"Відкрити","No active version":"Немає активної версії","Trading rules":"Торгові правила","Parse & create strategy":"Розібрати та створити стратегію",
  "Structured controls preview":"Попередній перегляд налаштувань","Market":"Ринок","Direction":"Напрямок","Entry timeframe":"Таймфрейм входу",
  "Entry model":"Модель входу","Risk / trade":"Ризик на угоду","Take profit":"Тейк-профіт","Management":"Керування","Unresolved":"Не уточнено",

  "Validation":"Перевірка","Test an exact immutable strategy version against historical data.":"Перевір точну незмінну версію стратегії на історичних даних.",
  "See how the strategy behaves before it touches runtime.":"Подивись, як стратегія поводиться до запуску runtime.",
  "Exact version":"Точна версія","Equity curve":"Крива капіталу","Trade audit":"Аудит угод",
  "Validation & performance":"Перевірка та результати","Strategy ID":"ID стратегії","Symbol":"Інструмент","Timeframe":"Таймфрейм",
  "Date from":"Дата від","Date to":"Дата до","Starting balance":"Початковий баланс","Spread (pips)":"Спред (піпси)",
  "Commission / lot":"Комісія / лот","Slippage (pips)":"Прослизання (піпси)","Create backtest":"Створити бектест","Run":"Запустити",

  "Version analysis":"Аналіз версій","Compare candidate strategy versions under the same conditions.":"Порівняй версії стратегії в однакових умовах.",
  "Know exactly what changed — and whether it improved.":"Точно знай, що змінилося і чи стало краще.","Same conditions":"Однакові умови",
  "Metric delta":"Зміна метрик","Schema diff":"Зміни схеми","Version comparison":"Порівняння версій","Compare immutable versions":"Порівняти незмінні версії",
  "Previous backtest ID":"ID попереднього бектесту","Candidate backtest ID":"ID нового бектесту","Compare versions":"Порівняти версії",

  "Account environment":"Середовище рахунку","Configure verified account constraints and pre-trade compliance.":"Налаштуй перевірені обмеження рахунку та передторгові перевірки.",
  "Trade inside the account rules — not around them.":"Торгуй у межах правил акаунта, а не в обхід них.",
  "Personal account or Prop Firm?":"Особистий рахунок чи Prop Firm?","Select the environment once. VELMONTAIRE applies the correct account constraints before execution.":"Обери тип рахунку один раз. VELMONTAIRE застосує потрібні обмеження до виконання.",
  "Personal account":"Особистий рахунок","Prop Firm account":"Prop-рахунок","Account type":"Тип рахунку","Firm":"Фірма","Program":"Програма",
  "Stage / Phase":"Етап / фаза","Account Size":"Розмір рахунку","Apply Prop Rules":"Застосувати Prop-правила","Not configured":"Не налаштовано",
  "Continue to MT5 →":"Перейти до MT5 →","News compliance":"Перевірка новин","Pre-trade news check":"Перевірка новин перед угодою",
  "Action":"Дія","Requested risk amount":"Запитаний ризик","Check Prop Risk":"Перевірити ризик",

  "Broker boundary":"Контур брокера","Manage the verified MetaTrader connection used by PAPER and LIVE.":"Керуй перевіреним підключенням MetaTrader для PAPER і LIVE.",
  "A controlled bridge between VELMONTAIRE and MT5.":"Контрольований міст між VELMONTAIRE і MT5.",
  "Connect your MT5 account":"Підключи свій MT5-рахунок","Personal account":"Особистий рахунок","Prop account":"Prop-рахунок",
  "MT5 login":"Логін MT5","MT5 server":"Сервер MT5","MT5 password":"Пароль MT5",
  "1. Save connection":"1. Зберегти підключення","2. Test connection":"2. Перевірити підключення",
  "Connection status":"Статус підключення","Not configured yet.":"Ще не налаштовано.","No verified MT5 connection.":"Немає перевіреного MT5-підключення.",
  "What happens next?":"Що далі?","Save credentials":"Збережи дані","Verify connection":"Перевір з'єднання","Start PAPER":"Запусти PAPER",
  "Authorize LIVE":"Дозволь LIVE","Continue to PAPER →":"Перейти до PAPER →",

  "Dry-run execution":"Тестове виконання","Test the runtime, not only the strategy.":"Перевір runtime, а не лише стратегію.",
  "Approved version":"Підтверджена версія","Runtime state":"Стан runtime","No live authority":"Без LIVE-доступу",
  "Bot ID":"ID бота","Approved strategy version":"Підтверджена версія стратегії","Start PAPER":"Запустити PAPER","PAPER stopped.":"PAPER зупинено.",

  "Live execution":"LIVE-виконання","LIVE starts only when every prerequisite is proven.":"LIVE запускається лише після підтвердження всіх умов.",
  "Explicit confirmation":"Явне підтвердження","Pause / Stop":"Пауза / Стоп","Strategy version ID":"ID версії стратегії",
  "Verified MT5 connection ID":"ID перевіреного MT5","Confirmation phrase":"Фраза підтвердження","Confirm LIVE":"Підтвердити LIVE",
  "Start LIVE":"Запустити LIVE","Pause":"Пауза","Stop":"Стоп","Refresh":"Оновити","Revoke LIVE":"Відкликати LIVE","LIVE not authorized.":"LIVE не дозволено.",

  "Production safety":"Production-безпека","Inspect failure state, recovery and reconciliation before new entries.":"Перевіряй стан помилок, відновлення та звірку до нових входів.",
  "Uncertain state means no new trade.":"Невизначений стан — жодних нових угод.","Crash recovery":"Відновлення після збою","Reconciliation":"Звірка стану",
  "Failure & recovery":"Помилки та відновлення","Connection status":"Статус з'єднання","Disconnect event":"Подія відключення",
  "Reconnect recovery":"Відновлення з'єднання","Restart recovery":"Відновлення після рестарту","Refresh safety state":"Оновити стан",

  "Plan management":"Керування тарифом","Subscription, usage and product entitlements in one surface.":"Підписка, використання та доступні функції — на одній сторінці.",
  "Know exactly what the workspace can use.":"Одразу видно, що доступно у твоєму тарифі.","Plan & billing":"Тариф і підписка",
  "Choose the plan that matches how you trade":"Обери тариф під свій стиль торгівлі","Refresh account":"Оновити акаунт","Current subscription":"Поточна підписка",
  "Loading…":"Завантаження…","Checking your account.":"Перевіряємо акаунт.","Choose CORE":"Обрати CORE","Choose PRO":"Обрати PRO","Choose ELITE":"Обрати ELITE",
  "At a glance":"Коротко","What changes between plans?":"Чим відрізняються тарифи?","Feature":"Функція",
  "PAPER trading":"PAPER-торгівля","Prop-firm rules":"Правила Prop Firm","LIVE execution":"LIVE-виконання","Advanced analytics":"Розширена аналітика","Priority support":"Пріоритетна підтримка",

  "Observability":"Моніторинг","Monitor runtime health and operator-visible production state.":"Стеж за станом runtime та production-системи.",
  "See the system state before it becomes a problem.":"Побач проблему до того, як вона вплине на виконання.","Runtime health":"Стан runtime",
  "Recovery stack":"Відновлення","Operator feed":"Стрічка подій","Recent system activity":"Останні події","Workspace initialized":"Робочий простір запущено",
  "Fail-closed runtime enabled":"Fail-closed runtime увімкнено","Recovery stack available":"Система відновлення готова","NOW":"ЗАРАЗ"
});

const DASH_SOURCE_TEXT = new WeakMap();
const DASH_SOURCE_ATTR = new WeakMap();
let dashLanguage = "en";
let translating = false;

function normalizedText(value) {
  return String(value || "").replace(/\s+/g, " ").trim();
}

function dictionaryFor(lang) {
  return DASH_TRANSLATIONS[lang] || {};
}

function translateTextNode(node, dict) {
  if (!node || node.nodeType !== Node.TEXT_NODE) return;
  const parent = node.parentElement;
  if (!parent || parent.closest("script,style,pre,code")) return;
  if (parent.matches("input,textarea,select,option")) return;

  if (!DASH_SOURCE_TEXT.has(node)) {
    const source = normalizedText(node.nodeValue);
    if (source) DASH_SOURCE_TEXT.set(node, source);
  }

  const source = DASH_SOURCE_TEXT.get(node);
  if (!source) return;

  const translated = dashLanguage === "en" ? source : dict[source];
  if (translated !== undefined) {
    const leading = /^\s*/.exec(node.nodeValue)?.[0] || "";
    const trailing = /\s*$/.exec(node.nodeValue)?.[0] || "";
    const nextValue = leading + translated + trailing;
    if (node.nodeValue !== nextValue) {
      node.nodeValue = nextValue;
    }
  }
}

function translateAttributes(element, dict) {
  if (!(element instanceof Element)) return;

  const attrs = ["placeholder", "title", "aria-label"];
  let stored = DASH_SOURCE_ATTR.get(element);
  if (!stored) {
    stored = {};
    attrs.forEach((attr) => {
      if (element.hasAttribute(attr)) stored[attr] = element.getAttribute(attr);
    });
    DASH_SOURCE_ATTR.set(element, stored);
  }

  attrs.forEach((attr) => {
    if (!(attr in stored)) return;
    const source = stored[attr];
    const translated = dashLanguage === "en" ? source : dict[source];
    if (
      translated !== undefined &&
      element.getAttribute(attr) !== translated
    ) {
      element.setAttribute(attr, translated);
    }
  });
}

function walkAndTranslate(root = document.body) {
  if (!root) return;
  const dict = dictionaryFor(dashLanguage);

  translating = true;
  try {
    if (root.nodeType === Node.TEXT_NODE) {
      translateTextNode(root, dict);
      return;
    }

    if (root instanceof Element) translateAttributes(root, dict);

    const walker = document.createTreeWalker(
      root,
      NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT
    );

    let node = walker.currentNode;
    while (node) {
      if (node.nodeType === Node.TEXT_NODE) translateTextNode(node, dict);
      else if (node instanceof Element) translateAttributes(node, dict);
      node = walker.nextNode();
    }
  } finally {
    translating = false;
  }
}

function setDashboardLanguage(lang) {
  dashLanguage = ["en", "ru", "uk"].includes(lang) ? lang : "en";
  localStorage.setItem(DASH_LANG_STORAGE, dashLanguage);
  document.documentElement.lang = dashLanguage === "uk" ? "uk" : dashLanguage;

  const current = document.querySelector("#dash-language-current");
  if (current) current.textContent = dashLanguage === "uk" ? "UA" : dashLanguage.toUpperCase();

  document.querySelectorAll("[data-dash-language]").forEach((button) => {
    button.classList.toggle("active", button.dataset.dashLanguage === dashLanguage);
  });

  walkAndTranslate(document.body);
}

function initDashboardLanguage() {
  const saved = localStorage.getItem(DASH_LANG_STORAGE);
  const browser = (navigator.language || "en").toLowerCase();
  const initial = saved || (browser.startsWith("ru") ? "ru" : browser.startsWith("uk") ? "uk" : "en");

  const button = document.querySelector("#dash-language-button");
  const menu = document.querySelector("#dash-language-menu");

  button?.addEventListener("click", () => {
    menu.hidden = !menu.hidden;
    button.setAttribute("aria-expanded", String(!menu.hidden));
  });

  menu?.querySelectorAll("[data-dash-language]").forEach((option) => {
    option.addEventListener("click", () => {
      setDashboardLanguage(option.dataset.dashLanguage);
      menu.hidden = true;
      button?.setAttribute("aria-expanded", "false");
    });
  });

  document.addEventListener("click", (event) => {
    if (!event.target.closest("#dash-language-switcher") && menu) {
      menu.hidden = true;
      button?.setAttribute("aria-expanded", "false");
    }
  });

  // Important:
  // Watch only newly-added DOM nodes.
  // Watching characterData here creates a self-triggering translation loop:
  // translation changes text -> observer fires -> translation changes text again.
  const observer = new MutationObserver((mutations) => {
    if (translating) return;

    translating = true;
    try {
      for (const mutation of mutations) {
        mutation.addedNodes.forEach((node) => {
          walkAndTranslate(node);
        });
      }
    } finally {
      translating = false;
    }
  });

  observer.observe(document.body, {
    subtree: true,
    childList: true,
  });

  setDashboardLanguage(initial);
}

document.addEventListener("DOMContentLoaded", initDashboardLanguage);
