const DASHBOARD_PAGES = {
  statistics: {
    path: "/dashboard",
    eyebrow: "Performance",
    title: "Statistics",
    subtitle: "Daily performance, trading quality and account health.",
    heroKicker: "DAILY PERFORMANCE / ACCOUNT ANALYTICS",
    heroTitle: "Know exactly how every trading day performed.",
    heroCopy: "See daily P/L, win rate, profit factor, drawdown and trade count from the execution data generated by your own workspace.",
    chips: ["Daily history", "No fake data", "Execution-log source"],
  },
  overview: {
    path: "/dashboard/overview",
    eyebrow: "Operator workspace",
    title: "Control center",
    subtitle: "Your trading system, runtime and account health in one place.",
    heroKicker: "VELMONTAIRE / OVERVIEW",
    heroTitle: "One workspace. Every execution boundary visible.",
    heroCopy: "Move from strategy design to backtest, broker connection and controlled runtime without losing sight of safety.",
    chips: ["Fail-closed core", "Immutable versions", "Paper → Live"],
  },
  strategy: {
    path: "/dashboard/strategy",
    eyebrow: "AI strategy builder",
    title: "Strategy",
    subtitle: "Describe the system naturally, then control every resolved rule.",
    heroKicker: "BUILD / STRUCTURE / COMPILE",
    heroTitle: "Turn trading language into an executable strategy.",
    heroCopy: "VELMONTAIRE parses the idea, surfaces ambiguity and keeps every important rule reviewable before compilation.",
    chips: ["Multilingual parser", "Structured controls", "Custom capabilities"],
  },
  "my-strategies": {
    path: "/dashboard/my-strategies",
    eyebrow: "Strategy library",
    title: "My Strategies",
    subtitle: "Your saved strategies, active versions and immutable history.",
    heroKicker: "SAVED / VERSIONED / USER-SCOPED",
    heroTitle: "Every strategy you create, ready when you return.",
    heroCopy: "Strategies are stored server-side under your account. Open a strategy, inspect version history or send its active version to Backtest.",
    chips: ["Server-side storage", "Immutable history", "Backtest ready"],
  },
  backtest: {
    path: "/dashboard/backtest",
    eyebrow: "Validation",
    title: "Backtest",
    subtitle: "Test an exact immutable strategy version against historical data.",
    heroKicker: "EVIDENCE BEFORE EXECUTION",
    heroTitle: "See how the strategy behaves before it touches runtime.",
    heroCopy: "Run controlled historical validation, inspect risk-adjusted metrics and audit every trade.",
    chips: ["Exact version", "Equity curve", "Trade audit"],
  },
  compare: {
    path: "/dashboard/compare",
    eyebrow: "Version analysis",
    title: "Compare",
    subtitle: "Compare candidate strategy versions under the same conditions.",
    heroKicker: "VERSION INTELLIGENCE",
    heroTitle: "Know exactly what changed — and whether it improved.",
    heroCopy: "Compare performance deltas and schema changes without mixing incompatible test conditions.",
    chips: ["Same conditions", "Metric delta", "Schema diff"],
  },
  "prop-rules": {
    path: "/dashboard/prop-rules",
    eyebrow: "Account environment",
    title: "Prop Rules",
    subtitle: "Configure verified account constraints and pre-trade compliance.",
    heroKicker: "POLICY / RISK / COMPLIANCE",
    heroTitle: "Trade inside the account rules — not around them.",
    heroCopy: "Keep prop policy server-owned while exposing the limits and checks the operator actually needs.",
    chips: ["CFD props", "Futures props", "News + risk checks"],
  },
  mt5: {
    path: "/dashboard/mt5",
    eyebrow: "Broker boundary",
    title: "MT5",
    subtitle: "Manage the verified MetaTrader connection used by PAPER and LIVE.",
    heroKicker: "BROKER CONNECTIVITY",
    heroTitle: "A controlled bridge between VELMONTAIRE and MT5.",
    heroCopy: "Credentials remain behind the secure boundary and execution modes depend on verified connectivity.",
    chips: ["Secure credentials", "Connection test", "Runtime boundary"],
  },
  paper: {
    path: "/dashboard/paper",
    eyebrow: "Dry-run execution",
    title: "PAPER",
    subtitle: "Run the approved strategy through the production runtime without LIVE authority.",
    heroKicker: "PRODUCTION LOGIC / ZERO LIVE AUTHORITY",
    heroTitle: "Test the runtime, not only the strategy.",
    heroCopy: "Use the same guarded execution path while removing live-market authority from the equation.",
    chips: ["Approved version", "Runtime state", "No live authority"],
  },
  live: {
    path: "/dashboard/live",
    eyebrow: "Live execution",
    title: "LIVE",
    subtitle: "Explicit authorization and controlled execution for the live account.",
    heroKicker: "PROTECTED EXECUTION",
    heroTitle: "LIVE starts only when every prerequisite is proven.",
    heroCopy: "Connection, strategy version, operator confirmation and runtime safety must align before execution is allowed.",
    chips: ["Explicit confirmation", "Pause / Stop", "Revocable authority"],
  },
  safety: {
    path: "/dashboard/safety",
    eyebrow: "Production safety",
    title: "Safety",
    subtitle: "Inspect failure state, recovery and reconciliation before new entries.",
    heroKicker: "FAIL-CLOSED CONTROL",
    heroTitle: "Uncertain state means no new trade.",
    heroCopy: "Disconnects, restart ambiguity and recovery failures stay visible and block unsafe continuation.",
    chips: ["Crash recovery", "Reconciliation", "Entry blocking"],
  },
  billing: {
    path: "/dashboard/billing",
    eyebrow: "Plan management",
    title: "Billing",
    subtitle: "Subscription, usage and product entitlements in one surface.",
    heroKicker: "PLAN / ACCESS / USAGE",
    heroTitle: "Know exactly what the workspace can use.",
    heroCopy: "Review subscription state, current usage and the capabilities unlocked by each plan.",
    chips: ["Entitlements", "Usage", "Sandbox checkout"],
  },
  telemetry: {
    path: "/dashboard/telemetry",
    eyebrow: "Observability",
    title: "Telemetry",
    subtitle: "Monitor runtime health and operator-visible production state.",
    heroKicker: "HEALTH / EVENTS / READINESS",
    heroTitle: "See the system state before it becomes a problem.",
    heroCopy: "Operational health, recovery readiness and execution safety converge into one monitoring surface.",
    chips: ["Runtime health", "Recovery stack", "Operator feed"],
  },
};

function currentPageKey() {
  const path = window.location.pathname.replace(/\/+$/, "") || "/dashboard";

  for (const [key, page] of Object.entries(DASHBOARD_PAGES)) {
    if (page.path === path) return key;
  }

  return "overview";
}

function renderPageShell() {
  const key = currentPageKey();
  const page = DASHBOARD_PAGES[key];

  document.querySelectorAll(".page-view").forEach((node) => {
    node.classList.toggle("is-active", node.dataset.page === key);
  });

  document.querySelectorAll(".menu a[data-route]").forEach((node) => {
    node.classList.toggle("active", node.dataset.route === key);
  });

  const eyebrow = document.querySelector("#page-eyebrow");
  const title = document.querySelector("#page-title");
  const subtitle = document.querySelector("#page-subtitle");

  if (eyebrow) eyebrow.textContent = page.eyebrow;
  if (title) title.textContent = page.title;
  if (subtitle) subtitle.textContent = page.subtitle;

  const hero = document.querySelector("#page-hero");
  if (hero) {
    hero.innerHTML = `
      <div class="hero-kicker">${page.heroKicker}</div>
      <div class="hero-title">${page.heroTitle}</div>
      <div class="hero-copy">${page.heroCopy}</div>
      <div class="hero-meta">
        ${page.chips.map((chip) => `<span class="hero-chip">${chip}</span>`).join("")}
      </div>
    `;
  }

  document.title = `VELMONTAIRE — ${page.title}`;
}

async function requireSession() {
  try {
    const response = await fetch("/api/auth/me", {
      credentials: "same-origin",
      cache: "no-store",
    });

    if (!response.ok) {
      window.location.replace("/login");
      return;
    }

    const data = await response.json();
    const userNode = document.querySelector("#user-id");

    if (userNode) {
      userNode.textContent = data.user_id;
      userNode.title = data.user_id;
    }
  } catch (_) {
    window.location.replace("/login");
  }
}

async function logout() {
  try {
    await fetch("/api/auth/logout", {
      method: "POST",
      credentials: "same-origin",
      cache: "no-store",
    });
  } finally {
    window.location.replace("/login");
  }
}

renderPageShell();

document
  .querySelector("#logout-button")
  ?.addEventListener("click", logout);

requireSession();
