async function L(p,o={}){let r=await fetch(p,{credentials:"same-origin",cache:"no-store",...o,headers:{"Content-Type":"application/json"}}),d=await r.json().catch(()=>({}));if(r.status===401){location.replace("/login");throw Error("authentication_required")}if(!r.ok)throw Error(d.error||"request_failed");return d}
function LS(t,e=false){let n=document.querySelector("#live-status");if(n){n.textContent=t;n.style.color=e?"#d6a4a4":"var(--gold)"}}
function LB(f){return{bot_id:f.elements.bot_id.value.trim(),strategy_version_id:f.elements.strategy_version_id.value.trim(),broker_connection_id:f.elements.broker_connection_id.value.trim()}}
document.querySelector("#live-confirm-form")?.addEventListener("submit",async e=>{e.preventDefault();let f=e.currentTarget,b=LB(f);b.confirmation_text=f.elements.confirmation_text.value;try{await L("/api/runtime/live/confirm",{method:"POST",body:JSON.stringify(b)});f.elements.confirmation_text.value="";LS("LIVE CONFIRMED for exact bot/version/connection.")}catch(x){LS(x.message,true)}});
document.querySelector("#live-start")?.addEventListener("click",async()=>{let f=document.querySelector("#live-confirm-form"),b=LB(f);try{await L("/api/runtime/live/start",{method:"POST",body:JSON.stringify(b)});LS("LIVE RUNNING");await refreshLive()}catch(x){LS(x.message,true)}});
async function liveCommand(action){let f=document.querySelector("#live-confirm-form"),id=f.elements.bot_id.value.trim();if(!id)return LS("bot_id_required",true);try{await L("/api/runtime/live/"+id+"/command",{method:"POST",body:JSON.stringify({action})});LS("LIVE "+action);await refreshLive()}catch(x){LS(x.message,true)}}
async function refreshLive(){let f=document.querySelector("#live-confirm-form"),id=f.elements.bot_id.value.trim();if(!id)return;try{let d=await L("/api/runtime/live/"+id+"/status");document.querySelector("#live-telemetry").textContent=JSON.stringify(d.runtime||{},null,2)}catch(x){LS(x.message,true)}}
document.querySelector("#live-pause")?.addEventListener("click",()=>liveCommand("PAUSE"));
document.querySelector("#live-stop")?.addEventListener("click",()=>liveCommand("STOP"));
document.querySelector("#live-refresh")?.addEventListener("click",refreshLive);
document.querySelector("#live-revoke")?.addEventListener("click",async()=>{let f=document.querySelector("#live-confirm-form"),id=f.elements.bot_id.value.trim();if(!id)return LS("bot_id_required",true);try{await L("/api/runtime/live/"+id+"/revoke",{method:"POST",body:"{}"});LS("LIVE authorization revoked.")}catch(x){LS(x.message,true)}});
